apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blackbox-exporter.fullname" . }}
data:
  config.yaml: |
    logger:
      level: {{ .Values.logLevel | quote}}
    nats:
      max_retries: {{ .Values.nats.max_retries }}
      retry_delay: {{ .Values.nats.retry_delay }}
      retry_backoff_multiplier: {{ .Values.nats.retry_backoff_multiplier }}
      is_jetstream: {{ .Values.nats.is_jetstream }}
      streams: {{ .Values.nats.streams | toYaml | nindent 8 }}
      url: {{ tpl (.Values.nats.url | toString) $ }}
      publish_interval: {{ .Values.nats.publish_interval | quote }}
      request_timeout: {{ .Values.nats.request_timeout | quote }}
      max_pub_acks_inflight: {{ .Values.nats.rmax_pub_acks_inflight | quote }}
      queue_subscription_group: {{ .Values.nats.queue_subscription_group | quote }}
      flush_timeout: {{ .Values.nats.flush_timeout | quote }}
      new_stream_allow: {{ .Values.nats.new_stream_allow }}
      region: {{ .Values.nats.region }}
      all_existing_streams: {{ .Values.nats.all_existing_streams }}
    metric:
      server:
        address: ":{{ .Values.metrics.port | default 8080 }}"
      enabled: true
